hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: false


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  maxAutoRetries: 0