#数据库配置

#PostgreSQL配置
#org.postgresql.Driver
#jdbc:postgresql://localhost:5432/SpringCloud

#MariaDB配置
#org.mariadb.jdbc.Driver
#jdbc:mariadb://localhost:3306/data_base

#配置数据库连接url用户密码
db:
  master:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/data_base
    username: root
    password: 111111qwe
  slave:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/data_base
    username: root
    password: 111111qwe

#################DRUID数据配置########################
druid:
  type: com.alibaba.druid.pool.DruidDataSource
  #写库配置
  master:
    driverClassName: ${db.master.driverClassName}
    url: ${db.master.url}
    username: ${db.master.username}
    password: ${db.master.password}
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
    filters: stat,wall
  #读库配置
  slave:
    driverClassName: ${db.slave.driverClassName}
    url: ${db.slave.url}
    username: ${db.slave.username}
    password: ${db.slave.password}
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
    filters: stat,wall
#################DRUID数据配置########################