#数据库配置

#PostgreSQL配置
#org.postgresql.Driver
#jdbc:postgresql://localhost:5432/SpringCloud

#MariaDB配置
#org.mariadb.jdbc.Driver
#jdbc:mariadb://localhost:3306/data_base

#配置数据库连接url用户密码
db:
  write:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://noageir.club:3306/data
    username: root
    password: 111111qaz
  read:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://noageir.club:3306/data
    username: root
    password: 111111qaz

#################DRUID数据配置########################
druid:
  type: com.alibaba.druid.pool.DruidDataSource
  #写库配置
  write:
    driverClassName: ${db.write.driverClassName}
    url: ${db.write.url}
    username: ${db.write.username}
    password: ${db.write.password}
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
    filters: stat,wall
  #读库配置
  read:
    driverClassName: ${db.read.driverClassName}
    url: ${db.read.url}
    username: ${db.read.username}
    password: ${db.read.password}
    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
    filters: stat,wall
#################DRUID数据配置########################