server:
  port: 10100
#---------------------------------------------------------------------
eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: true #是否从注册中心拉取注册服务列表
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10010/eureka/ #注册中心地址
#---------------------------------------------------------------------
info:
  version: 1.0.0
  app:
    name: ${spring.application.name}
  company:
    name: Noageir
  build:
    artifacitd: '@project.artifactId@'
    version: '@project.version@'
